{{- if .Values.deploy -}}
apiVersion: bitwarden-k8s-secrets-manager.demo.redhat.com/v1
kind: BitwardenSyncSecret
metadata:
  name: {{ include "poolboyScoring.name" . }}-scheduler-api-key
  namespace: {{ include "poolboyScoring.namespaceName" . }}
  labels:
    {{- include "poolboyScoring.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  data:
    CLUSTER_SCHEDULER_API_KEY:
      secret: {{ .Values.secrets.schedulerApiKey }}
      key: value
{{- end -}}
