{{- if and .Values.deploy .Values.metrics.enabled -}}
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ include "poolboyScoring.name" . }}-metrics-credentials
  namespace: {{ include "poolboyScoring.namespaceName" . }}
  labels:
    {{- include "poolboyScoring.labels" . | nindent 4 }}
  annotations:
    secret-generator.v1.mittwald.de/type: basic-auth
spec:
  forceRegenerate: false
  data:
    METRICS_USERNAME: {{ .Values.metrics.username }}
  fields:
  - fieldName: METRICS_PASSWORD
    encoding: "hex"
    length: "32"
{{- end -}}
